language: node_js

node_js:
  - '0.12'
  - iojs

before_install:
  - npm install -g gulp

script:
  - gulp
  - gulp production
  - npm test

env:
  global:
    - secure: "LjFkz3LL2OLGEiDsBW+luDwnKp1pZiCjmR9nd+QN9eIAfaWjyHhBGm2Eh0BIRxhwKLnTDcKtR/X/2qMFVSA0ne550ya6Ep0HBr6VAICGZTXep4lURyCzRuuKV/2NhsS5CRoc7Mp6puXV4jEWLpCS10w9sQLYy7ApYa9VgBPxUjU="
    - secure: "PHzsMTF5yz0NbAqYtVf+OXJlqFhX4eVH2j7eO/HrOgmLL3tTVP8851gHTVdQjXn6AHeYbFL7xj6XSFIQtbaFVV/3u56Dk5poug8xnpIyTm3BSHT9IcG5sCPKYT3/VuqyByFZbWTyCtqiFSs4H7xtjrViGHlxblwo2HUn8Y4f+FY="

after_success:
  "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://ftp.selcdn.ru/%D0%A4%D0%B0%D0%B9%D0%BB%D1%8B/build"
